// Code generated by MockGen. DO NOT EDIT.
// Source: bll/participant/controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	participant "github.com/byyjoww/leaderboard/bll/participant"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockParticipantController is a mock of ParticipantController interface.
type MockParticipantController struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantControllerMockRecorder
}

// MockParticipantControllerMockRecorder is the mock recorder for MockParticipantController.
type MockParticipantControllerMockRecorder struct {
	mock *MockParticipantController
}

// NewMockParticipantController creates a new mock instance.
func NewMockParticipantController(ctrl *gomock.Controller) *MockParticipantController {
	mock := &MockParticipantController{ctrl: ctrl}
	mock.recorder = &MockParticipantControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantController) EXPECT() *MockParticipantControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParticipantController) Create(ctx context.Context, leaderboardId uuid.UUID, externalId, name string, metadata map[string]string) (*participant.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, leaderboardId, externalId, name, metadata)
	ret0, _ := ret[0].(*participant.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockParticipantControllerMockRecorder) Create(ctx, leaderboardId, externalId, name, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParticipantController)(nil).Create), ctx, leaderboardId, externalId, name, metadata)
}

// Get mocks base method.
func (m *MockParticipantController) Get(ctx context.Context, leaderboardId uuid.UUID, externalId string) (*participant.RankedParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, leaderboardId, externalId)
	ret0, _ := ret[0].(*participant.RankedParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockParticipantControllerMockRecorder) Get(ctx, leaderboardId, externalId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockParticipantController)(nil).Get), ctx, leaderboardId, externalId)
}

// List mocks base method.
func (m *MockParticipantController) List(ctx context.Context, leaderboardId uuid.UUID, limit, offset int) ([]*participant.RankedParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, leaderboardId, limit, offset)
	ret0, _ := ret[0].([]*participant.RankedParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockParticipantControllerMockRecorder) List(ctx, leaderboardId, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockParticipantController)(nil).List), ctx, leaderboardId, limit, offset)
}

// Remove mocks base method.
func (m *MockParticipantController) Remove(ctx context.Context, leaderboardId uuid.UUID, externalId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, leaderboardId, externalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockParticipantControllerMockRecorder) Remove(ctx, leaderboardId, externalId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockParticipantController)(nil).Remove), ctx, leaderboardId, externalId)
}

// UpdateScore mocks base method.
func (m *MockParticipantController) UpdateScore(ctx context.Context, leaderboardId uuid.UUID, externalId string, score int) (*participant.RankedParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, leaderboardId, externalId, score)
	ret0, _ := ret[0].(*participant.RankedParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockParticipantControllerMockRecorder) UpdateScore(ctx, leaderboardId, externalId, score interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockParticipantController)(nil).UpdateScore), ctx, leaderboardId, externalId, score)
}
