// Code generated by MockGen. DO NOT EDIT.
// Source: dal/player/dal.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	player "github.com/byyjoww/leaderboard/dal/player"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPlayerDAL is a mock of PlayerDAL interface.
type MockParticipantDAL struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerDALMockRecorder
}

// MockPlayerDALMockRecorder is the mock recorder for MockPlayerDAL.
type MockPlayerDALMockRecorder struct {
	mock *MockParticipantDAL
}

// NewMockPlayerDAL creates a new mock instance.
func NewMockParticipantDAL(ctrl *gomock.Controller) *MockParticipantDAL {
	mock := &MockParticipantDAL{ctrl: ctrl}
	mock.recorder = &MockPlayerDALMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantDAL) EXPECT() *MockPlayerDALMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParticipantDAL) Create(player *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", player)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPlayerDALMockRecorder) Create(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParticipantDAL)(nil).Create), player)
}

// Delete mocks base method.
func (m *MockParticipantDAL) Delete(player *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", player)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlayerDALMockRecorder) Delete(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockParticipantDAL)(nil).Delete), player)
}

// Exists mocks base method.
func (m *MockParticipantDAL) Exists(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockPlayerDALMockRecorder) Exists(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockParticipantDAL)(nil).Exists), name)
}

// GetByPK mocks base method.
func (m *MockParticipantDAL) GetByPK(id uuid.UUID) (*player.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPK", id)
	ret0, _ := ret[0].(*player.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPK indicates an expected call of GetByPK.
func (mr *MockPlayerDALMockRecorder) GetByPK(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPK", reflect.TypeOf((*MockParticipantDAL)(nil).GetByPK), id)
}

// GetRankedByPK mocks base method.
func (m *MockParticipantDAL) GetRankedByPK(id uuid.UUID) (*player.RankedPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRankedByPK", id)
	ret0, _ := ret[0].(*player.RankedPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRankedByPK indicates an expected call of GetRankedByPK.
func (mr *MockPlayerDALMockRecorder) GetRankedByPK(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRankedByPK", reflect.TypeOf((*MockParticipantDAL)(nil).GetRankedByPK), id)
}

// List mocks base method.
func (m *MockParticipantDAL) List(leaderboardId uuid.UUID, limit, offset int) ([]*player.RankedPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", leaderboardId, limit, offset)
	ret0, _ := ret[0].([]*player.RankedPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPlayerDALMockRecorder) List(leaderboardId, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockParticipantDAL)(nil).List), leaderboardId, limit, offset)
}

// UpdateScore mocks base method.
func (m *MockParticipantDAL) UpdateScore(player *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", player)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockPlayerDALMockRecorder) UpdateScore(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockParticipantDAL)(nil).UpdateScore), player)
}
