environment: staging

logging:
  level: debug

http:
  api:
    address: 0.0.0.0:8080
    auth:
      enabled: true
      user: user
      pass: 
  telemetry:
    address: 0.0.0.0:9800
    auth:
      enabled: false
      user:
      pass:

postgres:
  host: localhost
  port: 9200
  user: user
  pass: 
  database: postgres
  poolSize: 20
  maxRetries: 3 
  connectionTimeout: 100s